### ISSUE TITLE
No way to define or change the avatar

### ISSUE THREAD

**Issue by DudeMcGee** [GeraldWodni/theforth.net#29]
There is no way to define an avatar while registering and no way to define or change an avatar afterwards.

**Comment by GeraldWodni** [comment]
The system uses [Gravatar](https://gravatar.com/). If you are not registered there, a randomized Avatar is created. To avoid tracking, the avatars are proxied and cached.

If you decide to register a Gravatar, feel free to bump this issue, and I will clear the cache, otherwise it will be cleared every few months.
